 - name: Update caches respository
   apt:
    update_cache: yes

 - name: Updating and installing core packages
   apt:
      name: "{{ packages }}"
   vars:
      packages:
      - make 
      - g++ 
      - git
      - curl 
      - vim 
      - libcairo2-dev 
      - libav-tools 
      - nfs-common
      - portmap